name: pypi

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/setup-python@v5
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: config
      run: |
        RELEASE=${GITHUB_REF##*/}
        sed -i -e "s/version=\".*\"/version=\"$RELEASE\"/" pyproject.toml
        echo $RELEASE
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        uv build
        uv publish